import Head from "next/head";
import Navbar from "./navbar";
import styles from '@/styles/Home.module.css'

export default function Layout({ children }) {
    return (
      <>
        <Head>
        <title>Amplify Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/amplifyicon.svg" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        {children}
        {/* <Footer /> */}
        </main>
      </>
    )
  }