import Head from "next/head";
import Navbar from "./navbar";
import styles from '@/styles/Home.module.css'
import { View } from "@aws-amplify/ui-react";

export default function Layout({ children, title, pages }) {

  return (
    <>
      <Head>
        <title>{title || "AWS Amplify"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/amplifyicon.svg" />
      </Head>
      <main className={styles.main}>
        <Navbar pages={pages} />
        {children}
        <View as="section" padding={'xxl'}>© Copyright, 2023</View>
      </main>
    </>
  )
}